"""first mirate

Revision ID: 57e0589092cd
Revises: 
Create Date: 2023-03-03 14:48:39.033300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57e0589092cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('create_nk', table_name='user')
    op.drop_index('is_delete_nk', table_name='user')
    op.drop_index('name_nk', table_name='user')
    op.drop_index('tel_num', table_name='user')
    op.drop_table('user')
    op.add_column('family', sa.Column('dd', sa.Integer(), nullable=True))
    op.alter_column('family', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='创建者id',
               existing_comment='创建人id',
               existing_nullable=True)
    op.alter_column('family', 'is_public',
               existing_type=mysql.TINYINT(),
               comment='是否公有，默认私有0',
               existing_comment='是否公开',
               existing_nullable=True)
    op.alter_column('family', 'name',
               existing_type=mysql.VARCHAR(length=50),
               comment='家人名称',
               existing_comment='姓名',
               existing_nullable=True)
    op.alter_column('family', 'birthday',
               existing_type=mysql.INTEGER(),
               comment='家人生日',
               existing_comment='生日',
               existing_nullable=True)
    op.alter_column('family', 'address',
               existing_type=mysql.VARCHAR(length=500),
               comment='现住址',
               existing_comment='现住地址',
               existing_nullable=True)
    op.alter_column('family', 'is_china_date',
               existing_type=mysql.TINYINT(),
               comment='是否是农历生日',
               existing_comment='是否是农历日期',
               existing_nullable=True)
    op.drop_index('is_delete_n', table_name='family')
    op.drop_index('is_public_n', table_name='family')
    op.drop_index('name_n', table_name='family')
    op.create_index(op.f('ix_family_create_time'), 'family', ['create_time'], unique=False)
    op.create_index(op.f('ix_family_is_delete'), 'family', ['is_delete'], unique=False)
    op.create_index(op.f('ix_family_name'), 'family', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_family_name'), table_name='family')
    op.drop_index(op.f('ix_family_is_delete'), table_name='family')
    op.drop_index(op.f('ix_family_create_time'), table_name='family')
    op.create_index('name_n', 'family', ['name'], unique=False)
    op.create_index('is_public_n', 'family', ['is_public'], unique=False)
    op.create_index('is_delete_n', 'family', ['is_delete'], unique=False)
    op.alter_column('family', 'is_china_date',
               existing_type=mysql.TINYINT(),
               comment='是否是农历日期',
               existing_comment='是否是农历生日',
               existing_nullable=True)
    op.alter_column('family', 'address',
               existing_type=mysql.VARCHAR(length=500),
               comment='现住地址',
               existing_comment='现住址',
               existing_nullable=True)
    op.alter_column('family', 'birthday',
               existing_type=mysql.INTEGER(),
               comment='生日',
               existing_comment='家人生日',
               existing_nullable=True)
    op.alter_column('family', 'name',
               existing_type=mysql.VARCHAR(length=50),
               comment='姓名',
               existing_comment='家人名称',
               existing_nullable=True)
    op.alter_column('family', 'is_public',
               existing_type=mysql.TINYINT(),
               comment='是否公开',
               existing_comment='是否公有，默认私有0',
               existing_nullable=True)
    op.alter_column('family', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='创建人id',
               existing_comment='创建者id',
               existing_nullable=True)
    op.drop_column('family', 'dd')
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True, comment='用户昵称'),
    sa.Column('birthday', mysql.INTEGER(), autoincrement=False, nullable=True, comment='生日'),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True, comment='现住地址'),
    sa.Column('tel_num', mysql.BIGINT(), autoincrement=False, nullable=True, comment='电话号码'),
    sa.Column('wechat_num', mysql.VARCHAR(length=50), nullable=True, comment='微信号'),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True, comment='邮箱地址'),
    sa.Column('is_delete', mysql.TINYINT(), autoincrement=False, nullable=True, comment='是否删除'),
    sa.Column('is_china_date', mysql.TINYINT(), autoincrement=False, nullable=True, comment='是否是农历生日'),
    sa.Column('create_time', mysql.INTEGER(), autoincrement=False, nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.INTEGER(), autoincrement=False, nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index('tel_num', 'user', ['tel_num'], unique=False)
    op.create_index('name_nk', 'user', ['name'], unique=False)
    op.create_index('is_delete_nk', 'user', ['is_delete'], unique=False)
    op.create_index('create_nk', 'user', ['create_time'], unique=False)
    # ### end Alembic commands ###
