"""sec migrate

Revision ID: d64d4ef68dfd
Revises: 57e0589092cd
Create Date: 2023-03-03 14:50:55.862023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd64d4ef68dfd'
down_revision = '57e0589092cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('family', 'dd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family', sa.Column('dd', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
